name: itokagimaru_daw
version: '1.0-SNAPSHOT'
main: io.github.itokagimaru.itokagimaru_daw.Itokagimaru_daw
api-version: '1.21'
commands:
  getDawItem:
    description: /getDawItem でdawを入手できるよ
    usage: /getDawItem
  getSheetMusic:
    description: /getSheetMusic で空白の楽譜を入手できるよ
    usage: /getSheetMusic
  getPlayItem:
    description: /getPlayItem でラジカセを入手できるよ
    usage: /getPlayItem
  getCassetteTape:
    description: /getCassetteTape でカセットテープを入手できるよ
    usage: /getCassetteTape
  setCassettesName:
    description: /setCassettesName でカセットテープに曲名を設定できるよ
    usage: /setCassettesName